sudo: required
services:
  - docker

before_install:
  - docker build -t jasunakum/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jasunakum/docker-react npm run test -- -- coverage
